# Generated by Django 3.0.4 on 2020-03-10 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_cargo'),
        ('registro', '0001_initial'),
        ('empleo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleo',
            name='empresa',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa'),
        ),
        migrations.AddField(
            model_name='empleo',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.Usuario'),
        ),
    ]
