# Generated by Django 3.0.4 on 2020-03-08 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='grupo',
            field=models.OneToOneField(default=12, on_delete=django.db.models.deletion.CASCADE, to='empresa.Grupo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subgrupo',
            name='grupo',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='empresa.Grupo'),
            preserve_default=False,
        ),
    ]
