# Generated by Django 3.0.4 on 2020-03-10 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20200308_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('sub_grupo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='empresa.Subgrupo')),
            ],
        ),
    ]
