# Generated by Django 3.0.4 on 2020-03-10 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_cargo'),
        ('recibo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='aporte_jubilatorio',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa'),
        ),
        migrations.AddField(
            model_name='recibo',
            name='frl',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='seguro_enfermedad',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
